name: ${project.artifactId}
main: ${project.mainclass}
version: ${project.version}
description: ${project.description}
dev-url: ${project.url}
#project lead
author: Diemex
#ensure that we are loaded after BeardStat
depend: [BeardStat]